### ISSUE TITLE
Alarm Date issue

### ISSUE THREAD

**Issue by ismemax** [NardHodo/PetFeeder-Main#17]
![image](https://github.com/NardHodo/PetFeeder-Main/assets/152414022/b2995cfd-6907-42ef-93e2-8d3e2e6da200)
Acronym nalang gamitin para masaya

**Comment by NardHodo** [comment]
![image](https://github.com/NardHodo/PetFeeder-Main/assets/133963030/112076c6-3be6-4c81-855c-b7529ffa37b5)
Done na po, Manager
